import zipfile
import json
import re
import os

ZIP_PATH = '/Users/linkunkun/Downloads/PaintLevels.zip'
OUTPUT_DIR = '/Users/linkunkun/fzd-fans.com/fzd-archive/public/data/dongdoku'

os.makedirs(OUTPUT_DIR, exist_ok=True)

with zipfile.ZipFile(ZIP_PATH) as z:
    all_files = z.namelist()
    map_files = [f for f in all_files if f.startswith('PaintLevels/Map_') and f.endswith('.json')]
    
    levels = {}
    
    # Process Map_1.json to Map_1000.json
    for f in map_files:
        m = re.search(r'Map_(\d+)\.json', f)
        if m:
            lvl_num = int(m.group(1))
            data = json.loads(z.read(f).decode('utf-8'))
            levels[lvl_num] = {
                'id': lvl_num,
                'size': data.get('size'),
                'regions': data.get('regions'),
                'solution': data.get('solution'),
                'difficulty': data.get('humanDifficulty', 'easy'),
                'diffText': data.get('humanDifficultyText', '简单'),
                'opening': data.get('opening', ''),
                'hints': data.get('logicSteps', [])
            }
    
    # Process Map_NewPlayer if exists as level 0
    if 'PaintLevels/Map_NewPlayer.json' in all_files:
        np_data = json.loads(z.read('PaintLevels/Map_NewPlayer.json').decode('utf-8'))
        levels[0] = {
            'id': 0,
            'size': np_data.get('size'),
            'regions': np_data.get('regions'),
            'solution': np_data.get('solution'),
            'difficulty': 'easy',
            'diffText': '教学',
            'opening': '每个颜色领地必须有且仅有1个咚，行与列各1个，且八方向不相碰。',
            'hints': []
        }

    total_levels = len(levels)
    print(f'Parsed {total_levels} levels.')
    
    # Generate manifest
    manifest = []
    # Sort by level id (1 to 1000, and 0 if exists)
    sorted_ids = sorted([k for k in levels.keys() if k > 0])
    if 0 in levels:
        sorted_ids = [0] + sorted_ids

    for lvl_id in sorted_ids:
        lvl = levels[lvl_id]
        manifest.append({
            'id': lvl['id'],
            'size': lvl['size'],
            'difficulty': lvl['difficulty'],
            'diffText': lvl['diffText']
        })
        
    with open(os.path.join(OUTPUT_DIR, 'manifest.json'), 'w', encoding='utf-8') as f:
        json.dump(manifest, f, separators=(',', ':'), ensure_ascii=False)
        
    # Split into packs of 50
    PACK_SIZE = 50
    # Levels 1-50 -> pack_0.json, 51-100 -> pack_1.json, etc.
    # Level 0 included in pack_0
    for pack_idx in range(20):
        start_id = pack_idx * PACK_SIZE + 1
        end_id = (pack_idx + 1) * PACK_SIZE
        pack_data = {}
        if pack_idx == 0 and 0 in levels:
            pack_data[0] = levels[0]
        for lid in range(start_id, end_id + 1):
            if lid in levels:
                pack_data[lid] = levels[lid]
        
        pack_path = os.path.join(OUTPUT_DIR, f'pack_{pack_idx}.json')
        with open(pack_path, 'w', encoding='utf-8') as f:
            json.dump(pack_data, f, separators=(',', ':'), ensure_ascii=False)
        print(f'Wrote pack_{pack_idx}.json (levels {start_id}-{end_id}) - size: {os.path.getsize(pack_path)/1024:.1f} KB')

    # Also output initial_levels.ts for pre-bundling levels 1..10
    first_10 = {lid: levels[lid] for lid in range(1, 11) if lid in levels}
    if 0 in levels:
        first_10[0] = levels[0]
    
    ts_code = f"// Auto-generated by extract_levels.py\nexport const INITIAL_LEVELS: Record<number, any> = {json.dumps(first_10, separators=(',', ':'), ensure_ascii=False)};\n"
    ts_path = '/Users/linkunkun/fzd-fans.com/fzd-archive/src/components/dongdoku/initialLevels.ts'
    os.makedirs(os.path.dirname(ts_path), exist_ok=True)
    with open(ts_path, 'w', encoding='utf-8') as f:
        f.write(ts_code)
    print(f'Wrote {ts_path}')

print("Done extraction successfully.")
